/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "bg-white",
    "border-4",
    "border-black",
    "border-[#000000]",
    "shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]",
    "hover:translate-x-[3px]",
    "hover:translate-y-[3px]",
    "hover:shadow-[1px_1px_0px_0px_rgba(0,0,0,1)]",
    "transition-all",
    "duration-200",
    "px-6",
    "py-3",
    "font-bold",
    "text-[#000000]",
    "p-6",
    "px-4",
    "py-2",
    "w-full",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-[#000000]",
    "text-4xl",
    "font-black",
    "tracking-tight",
    "text-2xl",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#FF6B6B",
        secondary: "#4ECDC4",
        accent: "#FFE66D",
        background: "#F7F7F7",
        text: "#2C3E50",
        white: "#FFFFFF",
        black: "#000000",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)"],
        mono: ["var(--font-geist-mono)"],
      },
    },
  },
  plugins: [],
};
